version: '3.8'

volumes:
  pez_volume:

services:
  postgres:
    container_name: pez_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: PEZ
      POSTGRES_PASSWORD: PEZPassword 
      POSTGRES_DB: PEZDB
    ports:
      - "5432:5432"
    volumes:
      - pez_volume:/var/lib/postgresql/data/